title: The Quantum-Satoshi Foundation
description: The next step for humanity starts with the convergence of Quantum, AI and Blockchain technologies. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman